# Site settings
title: LogosCaller
email: logoscaller@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Integrating AI into the details of life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://logoscaller.com" # the base hostname & protocol for your site
repository: logoscaller-oss/logoscaller-oss.github.io

twitter_username:
github_username: logoscaller-oss

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
